apiVersion: v1
kind: ConfigMap
metadata:
  name: pern-config
  namespace: pern
data:
  NODE_ENV: production
  SERVER_PORT: "8000"
  CLIENT_PORT: "3000"
  POSTGRES_USER: postgres
  POSTGRES_DB: inventory
  CORS_ORIGIN: http://localhost:3000
